spring.application.name=PiProject
### DATABASE ###
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/PI?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
server.port=9090

### JPA / HIBERNATE ###
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# SMTP Server Configuration
spring.mail.host=gru.o2switch.net
spring.mail.port=465
spring.mail.username=testing@gune0984.odns.fr
spring.mail.password=Wellupassword
management.health.mail.enabled=false

# Enable SSL/TLS
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.ssl.enable=true
